# Generated by Django 5.0.6 on 2024-08-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_product_image_cart_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Laptops', 'Laptops'), ("Women's Top Wear", "Women's Top Wear"), ("Women's Bottom Wear", "Women's Bottom Wear"), ("Men's Top Wear", "Men's Top Wear"), ("Men's Bottom Wear", "Men's Bottom Wear")], max_length=20),
        ),
    ]
